// Generated by Apple Swift version 1.2 (swiftlang-602.0.49.6 clang-602.0.49)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
#if __has_feature(nullability)
#  define SWIFT_NULLABILITY(X) X
#else
# if !defined(__nonnull)
#  define __nonnull
# endif
# if !defined(__nullable)
#  define __nullable
# endif
# if !defined(__null_unspecified)
#  define __null_unspecified
# endif
#  define SWIFT_NULLABILITY(X)
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import UIKit;
@import CoreGraphics;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSDictionary;

SWIFT_CLASS("_TtC14MercadoPagoSDK7Address")
@interface Address : NSObject
@property (nonatomic, copy) NSString * __nullable streetName;
@property (nonatomic, copy) NSString * __nullable zipCode;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (Address * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
@end

@class Cause;

SWIFT_CLASS("_TtC14MercadoPagoSDK12ApiException")
@interface ApiException : NSObject
@property (nonatomic) Cause * __null_unspecified cause;
@property (nonatomic, copy) NSString * __null_unspecified error;
@property (nonatomic, copy) NSString * __null_unspecified message;
@property (nonatomic) NSInteger status;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSData;
@class NSString;

SWIFT_CLASS("_TtC14MercadoPagoSDK12Serializable")
@interface Serializable : NSObject
- (NSDictionary * __nonnull)toDictionary;
- (NSData * __nonnull)toJson;
- (NSString * __null_unspecified)toJsonString;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK3Bin")
@interface Bin : Serializable
@property (nonatomic, copy) NSString * __null_unspecified exclusionPattern;
@property (nonatomic, copy) NSString * __null_unspecified installmentsPattern;
@property (nonatomic, copy) NSString * __null_unspecified pattern;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (Bin * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
@end

@class Cardholder;
@class NSDate;
@class PaymentMethod;
@class Issuer;
@class SecurityCode;

SWIFT_CLASS("_TtC14MercadoPagoSDK4Card")
@interface Card : NSObject
@property (nonatomic) Cardholder * __nullable cardHolder;
@property (nonatomic, copy) NSString * __nullable customerId;
@property (nonatomic) NSDate * __nullable dateCreated;
@property (nonatomic) NSDate * __nullable dateLastUpdated;
@property (nonatomic) NSInteger expirationMonth;
@property (nonatomic) NSInteger expirationYear;
@property (nonatomic, copy) NSString * __nullable firstSixDigits;
@property (nonatomic) int64_t _id;
@property (nonatomic, copy) NSString * __nullable lastFourDigits;
@property (nonatomic) PaymentMethod * __nullable paymentMethod;
@property (nonatomic) Issuer * __nullable issuer;
@property (nonatomic) SecurityCode * __nullable securityCode;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (Card * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (BOOL)isSecurityCodeRequired;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK10CardIssuer")
@interface CardIssuer : NSObject
@property (nonatomic, copy) NSString * __null_unspecified _id;
@property (nonatomic, copy) NSString * __null_unspecified name;
@property (nonatomic, copy) NSArray * __null_unspecified labels;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWith_id:(NSString * __nonnull)_id name:(NSString * __nullable)name labels:(NSArray * __nonnull)labels OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK10CardNumber")
@interface CardNumber : Serializable
@property (nonatomic) NSInteger length;
@property (nonatomic, copy) NSString * __null_unspecified validation;
+ (CardNumber * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class Device;
@class NSError;
@class IdentificationType;

SWIFT_CLASS("_TtC14MercadoPagoSDK9CardToken")
@interface CardToken : NSObject
@property (nonatomic, copy) NSString * __nullable cardNumber;
@property (nonatomic, copy) NSString * __nullable securityCode;
@property (nonatomic) NSInteger expirationMonth;
@property (nonatomic) NSInteger expirationYear;
@property (nonatomic) Cardholder * __nullable cardholder;
@property (nonatomic) Device * __nullable device;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCardNumber:(NSString * __nullable)cardNumber expirationMonth:(NSInteger)expirationMonth expirationYear:(NSInteger)expirationYear securityCode:(NSString * __nullable)securityCode cardholderName:(NSString * __nonnull)cardholderName docType:(NSString * __nonnull)docType docNumber:(NSString * __nonnull)docNumber OBJC_DESIGNATED_INITIALIZER;
- (NSString * __nullable)normalizeCardNumber:(NSString * __nullable)number;
- (BOOL)validate;
- (BOOL)validate:(BOOL)includeSecurityCode;
- (NSError * __nullable)validateCardNumber;
- (NSError * __nullable)validateCardNumber:(PaymentMethod * __nonnull)paymentMethod;
- (NSError * __nullable)validateSecurityCode;
- (NSError * __nullable)validateSecurityCode:(NSString * __nullable)securityCode;
- (NSError * __nullable)validateSecurityCodeWithPaymentMethod:(PaymentMethod * __nonnull)paymentMethod;
- (NSError * __nullable)validateSecurityCodeWithPaymentMethod:(NSString * __nonnull)securityCode paymentMethod:(PaymentMethod * __nonnull)paymentMethod bin:(NSString * __nonnull)bin;
- (NSError * __nullable)validateExpiryDate;
- (NSError * __nullable)validateExpiryDate:(NSInteger)month year:(NSInteger)year;
- (BOOL)validateExpMonth:(NSInteger)month;
- (BOOL)validateExpYear:(NSInteger)year;
- (NSError * __nullable)validateIdentification;
- (NSError * __nullable)validateIdentificationType;
- (NSError * __nullable)validateIdentificationNumber;
- (NSError * __nullable)validateIdentificationNumber:(IdentificationType * __nullable)identificationType;
- (NSError * __nullable)validateCardholderName;
- (BOOL)hasYearPassed:(NSInteger)year;
- (BOOL)hasMonthPassed:(NSInteger)year month:(NSInteger)month;
- (NSInteger)normalizeYear:(NSInteger)year;
- (BOOL)checkLuhn:(NSString * __nonnull)cardNumber;
- (NSString * __nullable)getBin;
- (NSString * __nonnull)toJSONString;
@end

@class Identification;

SWIFT_CLASS("_TtC14MercadoPagoSDK10Cardholder")
@interface Cardholder : NSObject
@property (nonatomic, copy) NSString * __nullable name;
@property (nonatomic) Identification * __nullable identification;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (Cardholder * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (NSString * __nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Cause")
@interface Cause : NSObject
@property (nonatomic, copy) NSString * __null_unspecified code;
@property (nonatomic, copy) NSString * __null_unspecified _description;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSCoder;

SWIFT_CLASS("_TtC14MercadoPagoSDK34CongratsPaymentMethodTableViewCell")
@interface CongratsPaymentMethodTableViewCell : UITableViewCell
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end

@class UITableView;
@class NSIndexPath;
@class Payment;

SWIFT_CLASS("_TtC14MercadoPagoSDK22CongratsViewController")
@interface CongratsViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate>
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)declareAndInitCells;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (void)_setTitle:(Payment * __nonnull)payment;
- (void)_setIcon:(Payment * __nonnull)payment;
- (void)setDescription:(Payment * __nonnull)payment;
- (void)setAmount:(Payment * __nonnull)payment;
- (void)setPaymentId:(Payment * __nonnull)payment;
- (void)setPaymentMethodDescription:(Payment * __nonnull)payment;
- (void)setDateCreated:(Payment * __nonnull)payment;
- (void)setButtonText:(Payment * __nonnull)payment;
- (void)submitForm;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK8Currency")
@interface Currency : NSObject
@property (nonatomic, copy) NSString * __null_unspecified _id;
@property (nonatomic, copy) NSString * __null_unspecified _description;
@property (nonatomic, copy) NSString * __null_unspecified symbol;
@property (nonatomic) NSInteger decimalPlaces;
@end

@class Phone;

SWIFT_CLASS("_TtC14MercadoPagoSDK8Customer")
@interface Customer : NSObject
@property (nonatomic) Address * __nullable address;
@property (nonatomic, copy) NSArray * __nullable cards;
@property (nonatomic, copy) NSString * __nullable _description;
@property (nonatomic) NSDate * __nullable dateCreated;
@property (nonatomic) NSDate * __nullable dateLastUpdated;
@property (nonatomic, copy) NSString * __nullable email;
@property (nonatomic, copy) NSString * __nullable firstName;
@property (nonatomic, copy) NSString * __nullable _id;
@property (nonatomic) Identification * __nullable identification;
@property (nonatomic, copy) NSString * __nullable lastName;
@property (nonatomic) NSDictionary * __nullable metadata;
@property (nonatomic) Phone * __nullable phone;
@property (nonatomic) NSDate * __nullable registrationDate;
+ (Customer * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27CustomerCardsViewController")
@interface CustomerCardsViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCards:(NSArray * __nullable)cards callback:(void (^ __nonnull)(Card * __nullable))callback OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)loadCards;
- (void)newCard;
@end

@class Fingerprint;

SWIFT_CLASS("_TtC14MercadoPagoSDK6Device")
@interface Device : NSObject
@property (nonatomic) Fingerprint * __null_unspecified fingerprint;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * __nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK8Discount")
@interface Discount : NSObject
@property (nonatomic) int64_t amountOff;
@property (nonatomic) int64_t couponAmount;
@property (nonatomic, copy) NSString * __null_unspecified currencyId;
@property (nonatomic) NSInteger _id;
@property (nonatomic, copy) NSString * __null_unspecified name;
@property (nonatomic) int64_t percentOff;
+ (Discount * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18ErrorTableViewCell")
@interface ErrorTableViewCell : UITableViewCell
@property (nonatomic) CGFloat height;
- (void)setError:(NSString * __nullable)error;
- (void)focus;
- (BOOL)hasError;
- (CGFloat)getHeight;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK10FeesDetail")
@interface FeesDetail : NSObject
@property (nonatomic) double amount;
@property (nonatomic) double amountRefunded;
@property (nonatomic, copy) NSString * __null_unspecified feePayer;
@property (nonatomic, copy) NSString * __null_unspecified type;
+ (FeesDetail * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK11Fingerprint")
@interface Fingerprint : NSObject
@property (nonatomic, copy) NSDictionary * __nullable fingerprint;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * __nonnull)toJSONString;
- (NSDictionary * __nonnull)deviceFingerprint;
- (NSArray * __nullable)devicesID;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18MercadoPagoService")
@interface MercadoPagoService : NSObject
- (void)request:(NSString * __nonnull)uri params:(NSString * __nullable)params body:(id __nullable)body method:(NSString * __nonnull)method success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
@end

@class SavedCardToken;

SWIFT_CLASS("_TtC14MercadoPagoSDK14GatewayService")
@interface GatewayService : MercadoPagoService
- (void)getTokenWithUrl:(NSString * __nonnull)url method:(NSString * __nonnull)method public_key:(NSString * __nonnull)public_key savedCardToken:(SavedCardToken * __nonnull)savedCardToken success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (void)getTokenWithUrl:(NSString * __nonnull)url method:(NSString * __nonnull)method public_key:(NSString * __nonnull)public_key cardToken:(CardToken * __nonnull)cardToken success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK16GenericErrorView")
@interface GenericErrorView : UIView
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setErrorMessage:(NSString * __nonnull)errorMessage;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14Identification")
@interface Identification : NSObject
@property (nonatomic, copy) NSString * __nullable type;
@property (nonatomic, copy) NSString * __nullable number;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithType:(NSString * __nullable)type number:(NSString * __nullable)number OBJC_DESIGNATED_INITIALIZER;
+ (Identification * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (NSString * __nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK21IdentificationService")
@interface IdentificationService : MercadoPagoService
- (void)getIdentificationTypesWithMethod:(NSString * __nonnull)method uri:(NSString * __nonnull)uri public_key:(NSString * __nullable)public_key privateKey:(NSString * __nullable)privateKey success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18IdentificationType")
@interface IdentificationType : NSObject
@property (nonatomic, copy) NSString * __nullable _id;
@property (nonatomic, copy) NSString * __nullable name;
@property (nonatomic, copy) NSString * __nullable type;
@property (nonatomic) NSInteger minLength;
@property (nonatomic) NSInteger maxLength;
+ (IdentificationType * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PayerCost;

SWIFT_CLASS("_TtC14MercadoPagoSDK11Installment")
@interface Installment : NSObject
@property (nonatomic) Issuer * __null_unspecified issuer;
@property (nonatomic, copy) NSArray * __null_unspecified payerCosts;
@property (nonatomic, copy) NSString * __null_unspecified paymentMethodId;
@property (nonatomic, copy) NSString * __null_unspecified paymentTypeId;
+ (Installment * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK24InstallmentTableViewCell")
@interface InstallmentTableViewCell : UITableViewCell
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithPayerCost:(PayerCost * __nonnull)payerCost amount:(double)amount;
@end

@class NSBundle;

SWIFT_CLASS("_TtC14MercadoPagoSDK26InstallmentsViewController")
@interface InstallmentsViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK6Issuer")
@interface Issuer : NSObject
@property (nonatomic, copy) NSString * __nullable name;
+ (Issuer * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK19IssuerTableViewCell")
@interface IssuerTableViewCell : UITableViewCell
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithIssuer:(Issuer * __nonnull)issuer;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK21IssuersViewController")
@interface IssuersViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK4Item")
@interface Item : NSObject
@property (nonatomic, copy) NSString * __null_unspecified _id;
@property (nonatomic) NSInteger quantity;
@property (nonatomic) double unitPrice;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWith_id:(NSString * __nonnull)_id quantity:(NSInteger)quantity unitPrice:(double)unitPrice OBJC_DESIGNATED_INITIALIZER;
- (NSString * __nonnull)toJSONString;
@end

@class Setting;
@class UITextField;

SWIFT_CLASS("_TtC14MercadoPagoSDK25MPCardNumberTableViewCell")
@interface MPCardNumberTableViewCell : ErrorTableViewCell <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UITextField * __null_unspecified cardNumberTextField;
@property (nonatomic) Setting * __null_unspecified setting;
- (void)focus;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString * __null_unspecified)getCardNumber;
- (void)setIcon:(NSString * __nullable)pmId;
- (void)_setSetting:(Setting * __null_unspecified)setting;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate> __nonnull)delegate;
- (BOOL)textField:(UITextField * __nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * __nonnull)string;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK29MPCardholderNameTableViewCell")
@interface MPCardholderNameTableViewCell : ErrorTableViewCell
@property (nonatomic, weak) IBOutlet UITextField * __null_unspecified cardholderNameTextField;
- (void)focus;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString * __null_unspecified)getCardholderName;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate> __nonnull)delegate;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK29MPExpirationDateTableViewCell")
@interface MPExpirationDateTableViewCell : ErrorTableViewCell <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UITextField * __null_unspecified expirationDateTextField;
- (void)focus;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSInteger)getExpirationMonth;
- (NSInteger)getExpirationYear;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate> __nonnull)delegate;
- (BOOL)textField:(UITextField * __nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * __nonnull)string;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27MPInstallmentsTableViewCell")
@interface MPInstallmentsTableViewCell : UITableViewCell
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithPayerCost:(PayerCost * __nullable)payerCost amount:(double)amount;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK33MPPaymentMethodEmptyTableViewCell")
@interface MPPaymentMethodEmptyTableViewCell : UITableViewCell
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK28MPPaymentMethodTableViewCell")
@interface MPPaymentMethodTableViewCell : UITableViewCell
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithCard:(Card * __nullable)card;
- (void)fillWithCardTokenAndPaymentMethod:(CardToken * __nullable)card paymentMethod:(PaymentMethod * __nullable)paymentMethod;
- (void)fillWithPaymentMethod:(PaymentMethod * __nullable)paymentMethod;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27MPSecurityCodeTableViewCell")
@interface MPSecurityCodeTableViewCell : ErrorTableViewCell
@property (nonatomic, weak) IBOutlet UITextField * __null_unspecified securityCodeTextField;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString * __null_unspecified)getSecurityCode;
- (void)fillWithPaymentMethod:(PaymentMethod * __nonnull)pm;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK9MPToolbar")
@interface MPToolbar : UIToolbar
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIPickerView;

SWIFT_CLASS("_TtC14MercadoPagoSDK21MPUserIdTableViewCell")
@interface MPUserIdTableViewCell : ErrorTableViewCell <UITextFieldDelegate, UIPickerViewDataSource, UIPickerViewDelegate>
@property (nonatomic, weak) IBOutlet UITextField * __null_unspecified userIdTypeTextField;
@property (nonatomic, weak) IBOutlet UITextField * __null_unspecified userIdValueTextField;
@property (nonatomic) IBOutlet UIPickerView * __null_unspecified pickerIdentificationType;
@property (nonatomic, copy) NSArray * __nonnull identificationTypes;
@property (nonatomic) IdentificationType * __nullable identificationType;
- (void)focus;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * __nonnull)pickerView;
- (NSInteger)pickerView:(UIPickerView * __nonnull)pickerView numberOfRowsInComponent:(NSInteger)component;
- (NSString * __null_unspecified)pickerView:(UIPickerView * __nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component;
- (void)pickerView:(UIPickerView * __nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
- (BOOL)textFieldShouldBeginEditing:(UITextField * __nonnull)textField;
- (BOOL)textField:(UITextField * __nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * __nonnull)string;
- (void)setFormWithIndex:(NSInteger)row;
- (void)awakeFromNib;
- (void)_setIdentificationTypes:(NSArray * __nullable)identificationTypes;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString * __null_unspecified)getUserIdType;
- (NSString * __null_unspecified)getUserIdValue;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate> __nonnull)delegate;
@end

@class NewCardViewController;
@class PaymentMethodsViewController;
@class PromoViewController;
@class Token;
@class UINavigationController;

SWIFT_CLASS("_TtC14MercadoPagoSDK11MercadoPago")
@interface MercadoPago : NSObject
+ (NSString * __nonnull)PUBLIC_KEY;
+ (NSString * __nonnull)PRIVATE_KEY;
+ (NSInteger)ERROR_KEY_CODE;
+ (NSInteger)ERROR_API_CODE;
+ (NSInteger)ERROR_UNKNOWN_CODE;
+ (NSInteger)ERROR_NOT_INSTALLMENTS_FOUND;
+ (NSInteger)ERROR_PAYMENT;
@property (nonatomic, copy) NSString * __nullable privateKey;
@property (nonatomic, copy) NSString * __nullable publicKey;
@property (nonatomic, copy) NSString * __nullable paymentMethodId;
@property (nonatomic, copy) NSString * __nullable paymentTypeId;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithPublicKey:(NSString * __nonnull)publicKey OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithKeyType:(NSString * __nullable)keyType key:(NSString * __nullable)key OBJC_DESIGNATED_INITIALIZER;
+ (CustomerCardsViewController * __nonnull)startCustomerCardsViewController:(NSArray * __nonnull)cards callback:(void (^ __nonnull)(Card * __nullable))callback;
+ (NewCardViewController * __nonnull)startNewCardViewController:(NSString * __nonnull)keyType key:(NSString * __nonnull)key paymentMethod:(PaymentMethod * __nonnull)paymentMethod requireSecurityCode:(BOOL)requireSecurityCode callback:(void (^ __nonnull)(CardToken * __nonnull))callback;
+ (PaymentMethodsViewController * __nonnull)startPaymentMethodsViewController:(NSString * __nonnull)merchantPublicKey supportedPaymentTypes:(NSArray * __nonnull)supportedPaymentTypes callback:(void (^ __nonnull)(PaymentMethod * __nonnull))callback;
+ (IssuersViewController * __nonnull)startIssuersViewController:(NSString * __nonnull)merchantPublicKey paymentMethod:(PaymentMethod * __nonnull)paymentMethod callback:(void (^ __nonnull)(Issuer * __nonnull))callback;
+ (InstallmentsViewController * __nonnull)startInstallmentsViewController:(NSArray * __nonnull)payerCosts amount:(double)amount callback:(void (^ __nonnull)(PayerCost * __nullable))callback;
+ (CongratsViewController * __nonnull)startCongratsViewController:(Payment * __nonnull)payment paymentMethod:(PaymentMethod * __nonnull)paymentMethod;
+ (PromoViewController * __nonnull)startPromosViewController:(NSString * __nonnull)merchantPublicKey;
- (void)createNewCardToken:(CardToken * __nonnull)cardToken success:(void (^ __nonnull)(Token * __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (void)createToken:(SavedCardToken * __nonnull)savedCardToken success:(void (^ __nonnull)(Token * __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (void)getPaymentMethods:(void (^ __nonnull)(NSArray * __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (void)getIdentificationTypes:(void (^ __nonnull)(NSArray * __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (void)getIssuers:(NSString * __nonnull)paymentMethodId success:(void (^ __nonnull)(NSArray * __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (void)getPromos:(void (^ __nonnull)(NSArray * __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
+ (BOOL)isCardPaymentType:(NSString * __nonnull)paymentTypeId;
+ (NSBundle * __nullable)getBundle;
+ (CGRect)screenBoundsFixedToPortraitOrientation;
+ (void)showAlertViewWithError:(NSError * __nullable)error nav:(UINavigationController * __nullable)nav;
@end



SWIFT_CLASS("_TtC14MercadoPagoSDK15MerchantPayment")
@interface MerchantPayment : NSObject
@property (nonatomic) int64_t cardIssuerId;
@property (nonatomic, copy) NSString * __null_unspecified cardToken;
@property (nonatomic) NSInteger campaignId;
@property (nonatomic) NSInteger installments;
@property (nonatomic) Item * __null_unspecified item;
@property (nonatomic, copy) NSString * __null_unspecified merchantAccessToken;
@property (nonatomic, copy) NSString * __null_unspecified paymentMethodId;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithItem:(Item * __nonnull)item installments:(NSInteger)installments cardIssuerId:(int64_t)cardIssuerId token:(NSString * __nonnull)token paymentMethodId:(NSString * __nonnull)paymentMethodId campaignId:(NSInteger)campaignId merchantAccessToken:(NSString * __nonnull)merchantAccessToken OBJC_DESIGNATED_INITIALIZER;
- (NSString * __nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14MerchantServer")
@interface MerchantServer : NSObject
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (void)getCustomer:(NSString * __nonnull)merchantBaseUrl merchantGetCustomerUri:(NSString * __nonnull)merchantGetCustomerUri merchantAccessToken:(NSString * __nonnull)merchantAccessToken success:(void (^ __nonnull)(Customer * __nonnull))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
+ (void)createPayment:(NSString * __nonnull)merchantBaseUrl merchantPaymentUri:(NSString * __nonnull)merchantPaymentUri payment:(MerchantPayment * __nonnull)payment success:(void (^ __nonnull)(Payment * __nonnull))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
@end

@class NSMutableData;

SWIFT_CLASS("_TtC14MercadoPagoSDK15MerchantService")
@interface MerchantService : MercadoPagoService
@property (nonatomic) NSMutableData * __nonnull data;
- (void)getCustomerWithMethod:(NSString * __nonnull)method merchant_access_token:(NSString * __nonnull)merchant_access_token success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (void)createPaymentWithMethod:(NSString * __nonnull)method payment:(MerchantPayment * __nonnull)payment success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK21NewCardViewController")
@interface NewCardViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (NSInteger)getIndexForObject:(id __nonnull)object;
- (void)scrollToRow:(NSIndexPath * __nonnull)indexPath;
- (void)focusAndScrollForIndex:(NSInteger)index;
- (void)prev:(id __nullable)object;
- (void)next:(id __nullable)object;
- (void)done:(id __nullable)object;
- (void)prepareTableView;
- (void)submitForm;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (NSInteger)numberOfSectionsInTableView:(UITableView * __nonnull)tableView;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)viewDidLayoutSubviews;
- (void)tableView:(UITableView * __nonnull)tableView willDisplayCell:(UITableViewCell * __nonnull)cell forRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (BOOL)validateForm:(CardToken * __nonnull)cardToken;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Order")
@interface Order : NSObject
@property (nonatomic) NSInteger _id;
@property (nonatomic, copy) NSString * __null_unspecified type;
+ (Order * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK9PayerCost")
@interface PayerCost : NSObject
@property (nonatomic) NSInteger installments;
@property (nonatomic) double installmentRate;
@property (nonatomic, copy) NSArray * __null_unspecified labels;
@property (nonatomic) double minAllowedAmount;
@property (nonatomic) double maxAllowedAmount;
@property (nonatomic, copy) NSString * __null_unspecified recommendedMessage;
@property (nonatomic) double installmentAmount;
@property (nonatomic) double totalAmount;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithInstallments:(NSInteger)installments installmentRate:(double)installmentRate labels:(NSArray * __nonnull)labels minAllowedAmount:(double)minAllowedAmount maxAllowedAmount:(double)maxAllowedAmount recommendedMessage:(NSString * __null_unspecified)recommendedMessage installmentAmount:(double)installmentAmount totalAmount:(double)totalAmount OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (PayerCost * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
@end

@class Refund;
@class TransactionDetails;

SWIFT_CLASS("_TtC14MercadoPagoSDK7Payment")
@interface Payment : NSObject
@property (nonatomic, copy) NSString * __null_unspecified callForAuthorizeId;
@property (nonatomic) Card * __null_unspecified card;
@property (nonatomic, copy) NSString * __null_unspecified currencyId;
@property (nonatomic) NSDate * __null_unspecified dateApproved;
@property (nonatomic) NSDate * __null_unspecified dateCreated;
@property (nonatomic) NSDate * __null_unspecified dateLastUpdated;
@property (nonatomic, copy) NSString * __null_unspecified _description;
@property (nonatomic, copy) NSString * __null_unspecified externalReference;
@property (nonatomic, copy) NSArray * __null_unspecified feesDetails;
@property (nonatomic) NSInteger _id;
@property (nonatomic) NSInteger installments;
@property (nonatomic) NSObject * __null_unspecified metadata;
@property (nonatomic) NSDate * __null_unspecified moneyReleaseDate;
@property (nonatomic, copy) NSString * __null_unspecified notificationUrl;
@property (nonatomic) Order * __null_unspecified order;
@property (nonatomic, copy) NSString * __null_unspecified paymentMethodId;
@property (nonatomic, copy) NSString * __null_unspecified paymentTypeId;
@property (nonatomic, copy) NSArray * __null_unspecified refunds;
@property (nonatomic, copy) NSString * __null_unspecified statementDescriptor;
@property (nonatomic, copy) NSString * __null_unspecified status;
@property (nonatomic, copy) NSString * __null_unspecified statusDetail;
@property (nonatomic) double transactionAmount;
@property (nonatomic) double transactionAmountRefunded;
@property (nonatomic) TransactionDetails * __null_unspecified transactionDetails;
@property (nonatomic, copy) NSString * __null_unspecified collectorId;
@property (nonatomic) double couponAmount;
@property (nonatomic) int64_t differentialPricingId;
@property (nonatomic) NSInteger issuerId;
+ (Payment * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
+ (NSDate * __null_unspecified)getDateFromString:(NSString * __null_unspecified)string;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK24PaymentDateTableViewCell")
@interface PaymentDateTableViewCell : UITableViewCell
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK22PaymentIDTableViewCell")
@interface PaymentIDTableViewCell : UITableViewCell
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK13PaymentMethod")
@interface PaymentMethod : Serializable
@property (nonatomic, copy) NSString * __null_unspecified _id;
@property (nonatomic, copy) NSString * __null_unspecified name;
@property (nonatomic, copy) NSString * __null_unspecified paymentTypeId;
@property (nonatomic, copy) NSArray * __null_unspecified settings;
@property (nonatomic, copy) NSArray * __null_unspecified additionalInfoNeeded;
- (BOOL)isIssuerRequired;
- (BOOL)isSecurityCodeRequired:(NSString * __nonnull)bin;
- (BOOL)isAdditionalInfoNeeded:(NSString * __null_unspecified)param;
+ (PaymentMethod * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK16PaymentMethodRow")
@interface PaymentMethodRow : NSObject
@property (nonatomic, copy) NSString * __nullable label;
@property (nonatomic) Card * __nullable card;
@property (nonatomic, copy) NSString * __nullable icon;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK26PaymentMethodTableViewCell")
@interface PaymentMethodTableViewCell : UITableViewCell
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setLabel:(NSString * __nonnull)label;
- (void)setImageWithName:(NSString * __nonnull)imageName;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK28PaymentMethodsViewController")
@interface PaymentMethodsViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14PaymentService")
@interface PaymentService : MercadoPagoService
- (void)getPaymentMethodsWithMethod:(NSString * __nonnull)method uri:(NSString * __nonnull)uri public_key:(NSString * __nonnull)public_key success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
- (void)getIssuersWithMethod:(NSString * __nonnull)method uri:(NSString * __nonnull)uri public_key:(NSString * __nonnull)public_key payment_method_id:(NSString * __nonnull)payment_method_id success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK25PaymentTotalTableViewCell")
@interface PaymentTotalTableViewCell : UITableViewCell
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Phone")
@interface Phone : NSObject
@property (nonatomic, copy) NSString * __nullable areaCode;
@property (nonatomic, copy) NSString * __nullable number;
+ (Phone * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK23PromoEmptyTableViewCell")
@interface PromoEmptyTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImageView;
@class UILabel;

SWIFT_CLASS("_TtC14MercadoPagoSDK18PromoTableViewCell")
@interface PromoTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified issuerImageView;
@property (nonatomic, weak) IBOutlet UILabel * __null_unspecified sharesSubtitle;
@property (nonatomic, weak) IBOutlet UILabel * __null_unspecified paymentMethodsSubtitle;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27PromoTyCDetailTableViewCell")
@interface PromoTyCDetailTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (void)setLabelWithIssuerName:(NSString * __nonnull)issuer legals:(NSString * __nonnull)legals;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK19PromoViewController")
@interface PromoViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithPublicKey:(NSString * __nonnull)publicKey OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK13PromosService")
@interface PromosService : MercadoPagoService
- (void)getPromosWithUrl:(NSString * __nonnull)url method:(NSString * __nonnull)method success:(void (^ __nonnull)(id __nullable))success failure:(void (^ __nullable)(NSError * __nonnull))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK22PromosTyCTableViewCell")
@interface PromosTyCTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK23PromosTyCViewController")
@interface PromosTyCViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithPromos:(NSArray * __nonnull)promos OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK6Refund")
@interface Refund : NSObject
@property (nonatomic) double amount;
@property (nonatomic) NSDate * __null_unspecified dateCreated;
@property (nonatomic) NSInteger _id;
@property (nonatomic) NSObject * __null_unspecified metadata;
@property (nonatomic) NSInteger paymentId;
@property (nonatomic, copy) NSString * __null_unspecified source;
@property (nonatomic, copy) NSString * __null_unspecified uniqueSequenceNumber;
+ (Refund * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14SavedCardToken")
@interface SavedCardToken : NSObject
@property (nonatomic, copy) NSString * __nullable cardId;
@property (nonatomic, copy) NSString * __nullable securityCode;
@property (nonatomic) Device * __nullable device;
@property (nonatomic) BOOL securityCodeRequired;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCardId:(NSString * __nonnull)cardId securityCode:(NSString * __nonnull)securityCode OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCardId:(NSString * __nonnull)cardId securityCode:(NSString * __nullable)securityCode securityCodeRequired:(BOOL)securityCodeRequired OBJC_DESIGNATED_INITIALIZER;
- (BOOL)validate;
- (BOOL)validateCardId;
- (BOOL)validateSecurityCode;
- (NSString * __nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK12SecurityCode")
@interface SecurityCode : Serializable
@property (nonatomic) NSInteger length;
@property (nonatomic, copy) NSString * __null_unspecified cardLocation;
@property (nonatomic, copy) NSString * __null_unspecified mode;
+ (SecurityCode * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC14MercadoPagoSDK7Setting")
@interface Setting : Serializable
@property (nonatomic) Bin * __null_unspecified bin;
@property (nonatomic) CardNumber * __null_unspecified cardNumber;
@property (nonatomic) SecurityCode * __null_unspecified securityCode;
+ (Setting * __nullable)getSettingByBin:(NSArray * __null_unspecified)settings bin:(NSString * __null_unspecified)bin;
+ (Setting * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Token")
@interface Token : NSObject
@property (nonatomic, copy) NSString * __null_unspecified _id;
@property (nonatomic, copy) NSString * __null_unspecified publicKey;
@property (nonatomic, copy) NSString * __null_unspecified cardId;
@property (nonatomic, copy) NSString * __null_unspecified luhnValidation;
@property (nonatomic, copy) NSString * __null_unspecified status;
@property (nonatomic, copy) NSString * __null_unspecified usedDate;
@property (nonatomic) NSInteger cardNumberLength;
@property (nonatomic) NSDate * __null_unspecified creationDate;
@property (nonatomic, copy) NSString * __null_unspecified truncCardNumber;
@property (nonatomic) NSInteger securityCodeLength;
@property (nonatomic) NSInteger expirationMonth;
@property (nonatomic) NSInteger expirationYear;
@property (nonatomic) NSDate * __null_unspecified lastModifiedDate;
@property (nonatomic) NSDate * __null_unspecified dueDate;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWith_id:(NSString * __nonnull)_id publicKey:(NSString * __nonnull)publicKey cardId:(NSString * __null_unspecified)cardId luhnValidation:(NSString * __null_unspecified)luhnValidation status:(NSString * __null_unspecified)status usedDate:(NSString * __null_unspecified)usedDate cardNumberLength:(NSInteger)cardNumberLength creationDate:(NSDate * __null_unspecified)creationDate truncCardNumber:(NSString * __null_unspecified)truncCardNumber securityCodeLength:(NSInteger)securityCodeLength expirationMonth:(NSInteger)expirationMonth expirationYear:(NSInteger)expirationYear lastModifiedDate:(NSDate * __null_unspecified)lastModifiedDate dueDate:(NSDate * __nullable)dueDate OBJC_DESIGNATED_INITIALIZER;
+ (Token * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18TransactionDetails")
@interface TransactionDetails : NSObject
@property (nonatomic) double couponAmount;
@property (nonatomic, copy) NSString * __null_unspecified externalResourceUrl;
@property (nonatomic, copy) NSString * __null_unspecified financialInstitution;
@property (nonatomic) double installmentAmount;
@property (nonatomic) double netReceivedAmount;
@property (nonatomic) double overpaidAmount;
@property (nonatomic) double totalPaidAmount;
+ (TransactionDetails * __nonnull)fromJSON:(NSDictionary * __nonnull)json;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIColor (SWIFT_EXTENSION(MercadoPagoSDK))
- (UIColor * __nonnull)UIColorFromRGB:(NSUInteger)rgbValue;
- (UIColor * __nonnull)errorCellColor;
- (UIColor * __nonnull)greenOkColor;
- (UIColor * __nonnull)redFailureColor;
- (UIColor * __nonnull)errorValidationTextColor;
- (UIColor * __nonnull)yellowFailureColor;
- (UIColor * __nonnull)blueMercadoPago;
- (UIColor * __nonnull)grayBaseText;
- (UIColor * __nonnull)grayDark;
- (UIColor * __nonnull)grayLight;
- (UIColor * __nonnull)grayLines;
- (UIColor * __nonnull)backgroundColor;
- (UIColor * __nonnull)white;
- (UIColor * __nonnull)installments;
@end


@interface UIDevice (SWIFT_EXTENSION(MercadoPagoSDK))
@end

@class UIActivityIndicatorView;

SWIFT_CLASS("_TtC14MercadoPagoSDK13UILoadingView")
@interface UILoadingView : UIView
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)rect text:(NSString * __nonnull)text OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) UILabel * __nonnull label;
@property (nonatomic) UIActivityIndicatorView * __nonnull spinner;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK19VaultViewController")
@interface VaultViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic) UILoadingView * __null_unspecified loadingView;
@property (nonatomic) Card * __nullable selectedCard;
@property (nonatomic) PayerCost * __nullable selectedPayerCost;
@property (nonatomic) CardToken * __nullable selectedCardToken;
@property (nonatomic) PaymentMethod * __nullable selectedPaymentMethod;
@property (nonatomic) Issuer * __nullable selectedIssuer;
@property (nonatomic) BOOL newCard;
@property (nonatomic, copy) NSArray * __nullable cards;
@property (nonatomic, copy) NSArray * __nullable payerCosts;
@property (nonatomic) BOOL securityCodeRequired;
@property (nonatomic) NSInteger securityCodeLength;
@property (nonatomic, copy) NSString * __nullable bin;
@property (nonatomic, copy) NSArray * __nullable supportedPaymentTypes;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)scrollToRow:(NSIndexPath * __nonnull)indexPath;
- (void)declareAndInitCells;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (CGFloat)tableView:(UITableView * __nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)loadPayerCosts;
- (void)submitForm;
@end

#pragma clang diagnostic pop
