// Generated by Swift version 1.1 (swift-600.0.57.4)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import UIKit;
@import CoreGraphics;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSDictionary;

SWIFT_CLASS("_TtC14MercadoPagoSDK7Address")
@interface Address : NSObject
@property (nonatomic, copy) NSString * streetName;
@property (nonatomic, copy) NSString * zipCode;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (Address *)fromJSON:(NSDictionary *)json;
@end

@class Cause;

SWIFT_CLASS("_TtC14MercadoPagoSDK12ApiException")
@interface ApiException : NSObject
@property (nonatomic) Cause * cause;
@property (nonatomic, copy) NSString * error;
@property (nonatomic, copy) NSString * message;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK3Bin")
@interface Bin : NSObject
@property (nonatomic, copy) NSString * exclusionPattern;
@property (nonatomic, copy) NSString * installmentsPattern;
@property (nonatomic, copy) NSString * pattern;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (Bin *)fromJSON:(NSDictionary *)json;
@end

@class Cardholder;
@class NSDate;
@class PaymentMethod;
@class Issuer;
@class SecurityCode;

SWIFT_CLASS("_TtC14MercadoPagoSDK4Card")
@interface Card : NSObject
@property (nonatomic) Cardholder * cardHolder;
@property (nonatomic, copy) NSString * customerId;
@property (nonatomic) NSDate * dateCreated;
@property (nonatomic) NSDate * dateLastUpdated;
@property (nonatomic, copy) NSString * firstSixDigits;
@property (nonatomic, copy) NSString * lastFourDigits;
@property (nonatomic) PaymentMethod * paymentMethod;
@property (nonatomic) Issuer * issuer;
@property (nonatomic) SecurityCode * securityCode;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (Card *)fromJSON:(NSDictionary *)json;
- (BOOL)isSecurityCodeRequired;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK10CardIssuer")
@interface CardIssuer : NSObject
@property (nonatomic, copy) NSString * id;
@property (nonatomic, copy) NSString * name;
@property (nonatomic, copy) NSArray * labels;
- (instancetype)initWithId:(NSString *)id name:(NSString *)name labels:(NSArray *)labels OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK10CardNumber")
@interface CardNumber : NSObject
@property (nonatomic, copy) NSString * validation;
+ (CardNumber *)fromJSON:(NSDictionary *)json;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class Device;
@class NSError;
@class IdentificationType;

SWIFT_CLASS("_TtC14MercadoPagoSDK9CardToken")
@interface CardToken : NSObject
@property (nonatomic, copy) NSString * cardNumber;
@property (nonatomic, copy) NSString * securityCode;
@property (nonatomic) Cardholder * cardholder;
@property (nonatomic) Device * device;
- (NSString *)normalizeCardNumber:(NSString *)number;
- (BOOL)validate;
- (BOOL)validate:(BOOL)includeSecurityCode;
- (NSError *)validateCardNumber;
- (NSError *)validateCardNumber:(PaymentMethod *)paymentMethod;
- (NSError *)validateSecurityCode;
- (NSError *)validateSecurityCode:(NSString *)securityCode;
- (NSError *)validateSecurityCodeWithPaymentMethod:(PaymentMethod *)paymentMethod;
- (NSError *)validateSecurityCodeWithPaymentMethod:(NSString *)securityCode paymentMethod:(PaymentMethod *)paymentMethod bin:(NSString *)bin;
- (NSError *)validateExpiryDate;
- (NSError *)validateIdentification;
- (NSError *)validateIdentificationType;
- (NSError *)validateIdentificationNumber;
- (NSError *)validateIdentificationNumber:(IdentificationType *)identificationType;
- (NSError *)validateCardholderName;
- (BOOL)hasMonthPassed:(NSInteger)year month:(NSInteger)month;
- (BOOL)checkLuhn:(NSString *)cardNumber;
- (NSString *)getBin;
- (NSString *)toJSONString;
@end

@class Identification;

SWIFT_CLASS("_TtC14MercadoPagoSDK10Cardholder")
@interface Cardholder : NSObject
@property (nonatomic, copy) NSString * name;
@property (nonatomic) Identification * identification;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (Cardholder *)fromJSON:(NSDictionary *)json;
- (NSString *)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Cause")
@interface Cause : NSObject
@property (nonatomic, copy) NSString * code;
@property (nonatomic, copy) NSString * _description;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSCoder;

SWIFT_CLASS("_TtC14MercadoPagoSDK34CongratsPaymentMethodTableViewCell")
@interface CongratsPaymentMethodTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;
@class NSIndexPath;
@class Payment;

SWIFT_CLASS("_TtC14MercadoPagoSDK22CongratsViewController")
@interface CongratsViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate>
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)declareAndInitCells;
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath;
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath;
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section;
- (void)setTitle:(Payment *)payment;
- (void)setIcon:(Payment *)payment;
- (void)setDescription:(Payment *)payment;
- (void)setAmount:(Payment *)payment;
- (void)setPaymentId:(Payment *)payment;
- (void)setPaymentMethodDescription:(Payment *)payment;
- (void)setDateCreated:(Payment *)payment;
- (void)setButtonText:(Payment *)payment;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK8Currency")
@interface Currency : NSObject
@property (nonatomic, copy) NSString * id;
@property (nonatomic, copy) NSString * _description;
@property (nonatomic, copy) NSString * symbol;
@end

@class Phone;

SWIFT_CLASS("_TtC14MercadoPagoSDK8Customer")
@interface Customer : NSObject
@property (nonatomic) Address * address;
@property (nonatomic, copy) NSArray * cards;
@property (nonatomic, copy) NSString * _description;
@property (nonatomic) NSDate * dateCreated;
@property (nonatomic) NSDate * dateLastUpdated;
@property (nonatomic, copy) NSString * email;
@property (nonatomic, copy) NSString * firstName;
@property (nonatomic, copy) NSString * id;
@property (nonatomic) Identification * identification;
@property (nonatomic, copy) NSString * lastName;
@property (nonatomic) NSDictionary * metadata;
@property (nonatomic) Phone * phone;
@property (nonatomic) NSDate * registrationDate;
+ (Customer *)fromJSON:(NSDictionary *)json;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27CustomerCardsViewController")
@interface CustomerCardsViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
- (instancetype)initWithCards:(NSArray *)cards callback:(void (^)(Card *))callback OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath;
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath;
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath;
- (void)loadCards;
- (void)newCard;
@end

@class Fingerprint;

SWIFT_CLASS("_TtC14MercadoPagoSDK6Device")
@interface Device : NSObject
@property (nonatomic) Fingerprint * fingerprint;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString *)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK8Discount")
@interface Discount : NSObject
@property (nonatomic, copy) NSString * currencyId;
@property (nonatomic, copy) NSString * name;
+ (Discount *)fromJSON:(NSDictionary *)json;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18ErrorTableViewCell")
@interface ErrorTableViewCell : UITableViewCell
@property (nonatomic) CGFloat height;
- (void)setError:(NSString *)error;
- (BOOL)hasError;
- (CGFloat)getHeight;
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK10FeesDetail")
@interface FeesDetail : NSObject
@property (nonatomic, copy) NSString * feePayer;
@property (nonatomic, copy) NSString * type;
+ (FeesDetail *)fromJSON:(NSDictionary *)json;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK11Fingerprint")
@interface Fingerprint : NSObject
@property (nonatomic, copy) NSDictionary * fingerprint;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString *)toJSONString;
- (NSDictionary *)deviceFingerprint;
- (NSArray *)devicesID;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18MercadoPagoService")
@interface MercadoPagoService : NSObject
- (void)request:(NSString *)uri params:(NSString *)params body:(id)body method:(NSString *)method success:(void (^)(id))success failure:(void (^)(NSError *))failure;
@end

@class SavedCardToken;

SWIFT_CLASS("_TtC14MercadoPagoSDK14GatewayService")
@interface GatewayService : MercadoPagoService
- (void)getTokenWithUrl:(NSString *)url method:(NSString *)method public_key:(NSString *)public_key savedCardToken:(SavedCardToken *)savedCardToken success:(void (^)(id))success failure:(void (^)(NSError *))failure;
- (void)getTokenWithUrl:(NSString *)url method:(NSString *)method public_key:(NSString *)public_key cardToken:(CardToken *)cardToken success:(void (^)(id))success failure:(void (^)(NSError *))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK16GenericErrorView")
@interface GenericErrorView : UIView
- (instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setErrorMessage:(NSString *)errorMessage;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14Identification")
@interface Identification : NSObject
@property (nonatomic, copy) NSString * type;
@property (nonatomic, copy) NSString * number;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithType:(NSString *)type number:(NSString *)number OBJC_DESIGNATED_INITIALIZER;
+ (Identification *)fromJSON:(NSDictionary *)json;
- (NSString *)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK21IdentificationService")
@interface IdentificationService : MercadoPagoService
- (void)getIdentificationTypesWithMethod:(NSString *)method uri:(NSString *)uri public_key:(NSString *)public_key privateKey:(NSString *)privateKey success:(void (^)(id))success failure:(void (^)(NSError *))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18IdentificationType")
@interface IdentificationType : NSObject
@property (nonatomic, copy) NSString * id;
@property (nonatomic, copy) NSString * name;
@property (nonatomic, copy) NSString * type;
+ (IdentificationType *)fromJSON:(NSDictionary *)json;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PayerCost;

SWIFT_CLASS("_TtC14MercadoPagoSDK11Installment")
@interface Installment : NSObject
@property (nonatomic) Issuer * issuer;
@property (nonatomic, copy) NSArray * payerCosts;
@property (nonatomic, copy) NSString * paymentMethodId;
@property (nonatomic, copy) NSString * paymentTypeId;
+ (Installment *)fromJSON:(NSDictionary *)json;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK24InstallmentTableViewCell")
@interface InstallmentTableViewCell : UITableViewCell
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithPayerCost:(PayerCost *)payerCost amount:(double)amount;
@end

@class NSBundle;

SWIFT_CLASS("_TtC14MercadoPagoSDK26InstallmentsViewController")
@interface InstallmentsViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath;
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath;
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK6Issuer")
@interface Issuer : NSObject
@property (nonatomic, copy) NSString * name;
+ (Issuer *)fromJSON:(NSDictionary *)json;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK19IssuerTableViewCell")
@interface IssuerTableViewCell : UITableViewCell
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithIssuer:(Issuer *)issuer;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK21IssuersViewController")
@interface IssuersViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath;
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath;
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK4Item")
@interface Item : NSObject
@property (nonatomic, copy) NSString * id;
- (instancetype)initWithId:(NSString *)id quantity:(NSInteger)quantity unitPrice:(double)unitPrice OBJC_DESIGNATED_INITIALIZER;
- (NSString *)toJSONString;
@end

@class Setting;
@class UITextField;

SWIFT_CLASS("_TtC14MercadoPagoSDK25MPCardNumberTableViewCell")
@interface MPCardNumberTableViewCell : ErrorTableViewCell <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UITextField * cardNumberTextField;
@property (nonatomic) BOOL hasError;
@property (nonatomic) Setting * setting;
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString *)getCardNumber;
- (void)setIcon:(NSString *)pmId;
- (void)setSetting:(Setting *)setting;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate>)delegate;
- (BOOL)textField:(UITextField *)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString *)string;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK29MPCardholderNameTableViewCell")
@interface MPCardholderNameTableViewCell : ErrorTableViewCell
@property (nonatomic) BOOL hasError;
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString *)getCardholderName;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate>)delegate;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK29MPExpirationDateTableViewCell")
@interface MPExpirationDateTableViewCell : ErrorTableViewCell <UITextFieldDelegate>
@property (nonatomic) BOOL hasError;
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate>)delegate;
- (BOOL)textField:(UITextField *)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString *)string;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27MPInstallmentsTableViewCell")
@interface MPInstallmentsTableViewCell : UITableViewCell
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithPayerCost:(PayerCost *)payerCost amount:(double)amount;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK33MPPaymentMethodEmptyTableViewCell")
@interface MPPaymentMethodEmptyTableViewCell : UITableViewCell
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK28MPPaymentMethodTableViewCell")
@interface MPPaymentMethodTableViewCell : UITableViewCell
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithCard:(Card *)card;
- (void)fillWithCardTokenAndPaymentMethod:(CardToken *)card paymentMethod:(PaymentMethod *)paymentMethod;
- (void)fillWithPaymentMethod:(PaymentMethod *)paymentMethod;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27MPSecurityCodeTableViewCell")
@interface MPSecurityCodeTableViewCell : ErrorTableViewCell
@property (nonatomic, weak) IBOutlet UITextField * securityCodeTextField;
@property (nonatomic) BOOL hasError;
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString *)getSecurityCode;
- (void)fillWithPaymentMethod:(PaymentMethod *)pm;
@end

@class UIPickerView;

SWIFT_CLASS("_TtC14MercadoPagoSDK21MPUserIdTableViewCell")
@interface MPUserIdTableViewCell : ErrorTableViewCell <UITextFieldDelegate, UIPickerViewDataSource, UIPickerViewDelegate>
@property (nonatomic) IBOutlet UIPickerView * pickerIdentificationType;
@property (nonatomic, copy) NSArray * identificationTypes;
@property (nonatomic) IdentificationType * identificationType;
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView *)pickerView;
- (NSInteger)pickerView:(UIPickerView *)pickerView numberOfRowsInComponent:(NSInteger)component;
- (NSString *)pickerView:(UIPickerView *)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component;
- (void)pickerView:(UIPickerView *)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
- (BOOL)textFieldShouldBeginEditing:(UITextField *)textField;
- (BOOL)textField:(UITextField *)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString *)string;
- (void)setFormWithIndex:(NSInteger)row;
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)setIdentificationTypes:(NSArray *)identificationTypes;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString *)getUserIdType;
- (NSString *)getUserIdValue;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate>)delegate;
@end

@class NewCardViewController;
@class PaymentMethodsViewController;
@class Token;
@class UINavigationController;

SWIFT_CLASS("_TtC14MercadoPagoSDK11MercadoPago")
@interface MercadoPago : NSObject
+ (NSString *)PUBLIC_KEY;
+ (NSString *)PRIVATE_KEY;
+ (NSInteger)ERROR_KEY_CODE;
+ (NSInteger)ERROR_API_CODE;
+ (NSInteger)ERROR_UNKNOWN_CODE;
@property (nonatomic, copy) NSString * privateKey;
@property (nonatomic, copy) NSString * publicKey;
@property (nonatomic, copy) NSString * paymentMethodId;
@property (nonatomic, copy) NSString * paymentTypeId;
- (instancetype)initWithPublicKey:(NSString *)publicKey OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithKeyType:(NSString *)keyType key:(NSString *)key OBJC_DESIGNATED_INITIALIZER;
+ (CustomerCardsViewController *)startCustomerCardsViewController:(NSArray *)cards callback:(void (^)(Card *))callback;
+ (NewCardViewController *)startNewCardViewController:(NSString *)keyType key:(NSString *)key paymentMethod:(PaymentMethod *)paymentMethod requireSecurityCode:(BOOL)requireSecurityCode callback:(void (^)(CardToken *))callback;
+ (PaymentMethodsViewController *)startPaymentMethodsViewController:(NSString *)merchantPublicKey supportedPaymentTypes:(NSArray *)supportedPaymentTypes callback:(void (^)(PaymentMethod *))callback;
+ (IssuersViewController *)startIssuersViewController:(NSString *)merchantPublicKey paymentMethod:(PaymentMethod *)paymentMethod callback:(void (^)(Issuer *))callback;
+ (InstallmentsViewController *)startInstallmentsViewController:(NSArray *)payerCosts amount:(double)amount callback:(void (^)(PayerCost *))callback;
+ (CongratsViewController *)startCongratsViewController:(Payment *)payment paymentMethod:(PaymentMethod *)paymentMethod;
- (void)createNewCardToken:(CardToken *)cardToken success:(void (^)(Token *))success failure:(void (^)(NSError *))failure;
- (void)createToken:(SavedCardToken *)savedCardToken success:(void (^)(Token *))success failure:(void (^)(NSError *))failure;
- (void)getPaymentMethods:(void (^)(NSArray *))success failure:(void (^)(NSError *))failure;
- (void)getIdentificationTypes:(void (^)(NSArray *))success failure:(void (^)(NSError *))failure;
- (void)getIssuers:(NSString *)paymentMethodId success:(void (^)(NSArray *))success failure:(void (^)(NSError *))failure;
+ (BOOL)isCardPaymentType:(NSString *)paymentTypeId;
+ (NSBundle *)getBundle;
+ (void)showAlertViewWithError:(NSError *)error nav:(UINavigationController *)nav;
@end



SWIFT_CLASS("_TtC14MercadoPagoSDK15MerchantPayment")
@interface MerchantPayment : NSObject
@property (nonatomic, copy) NSString * cardToken;
@property (nonatomic) Item * item;
@property (nonatomic, copy) NSString * merchantAccessToken;
@property (nonatomic, copy) NSString * paymentMethodId;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString *)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14MerchantServer")
@interface MerchantServer : NSObject
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (void)getCustomer:(NSString *)merchantBaseUrl merchantGetCustomerUri:(NSString *)merchantGetCustomerUri merchantAccessToken:(NSString *)merchantAccessToken success:(void (^)(Customer *))success failure:(void (^)(NSError *))failure;
+ (void)createPayment:(NSString *)merchantBaseUrl merchantPaymentUri:(NSString *)merchantPaymentUri payment:(MerchantPayment *)payment success:(void (^)(Payment *))success failure:(void (^)(NSError *))failure;
@end

@class NSMutableData;

SWIFT_CLASS("_TtC14MercadoPagoSDK15MerchantService")
@interface MerchantService : MercadoPagoService
@property (nonatomic) NSMutableData * data;
- (void)getCustomerWithMethod:(NSString *)method merchant_access_token:(NSString *)merchant_access_token success:(void (^)(id))success failure:(void (^)(NSError *))failure;
- (void)createPaymentWithMethod:(NSString *)method payment:(MerchantPayment *)payment success:(void (^)(id))success failure:(void (^)(NSError *))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK21NewCardViewController")
@interface NewCardViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (void)prepareTableView;
- (IBAction)submitForm;
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath;
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath;
- (BOOL)validateForm:(CardToken *)cardToken;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Order")
@interface Order : NSObject
@property (nonatomic, copy) NSString * type;
+ (Order *)fromJSON:(NSDictionary *)json;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK9PayerCost")
@interface PayerCost : NSObject
@property (nonatomic, copy) NSArray * labels;
@property (nonatomic, copy) NSString * recommendedMessage;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (PayerCost *)fromJSON:(NSDictionary *)json;
@end

@class Refund;
@class TransactionDetails;

SWIFT_CLASS("_TtC14MercadoPagoSDK7Payment")
@interface Payment : NSObject
@property (nonatomic, copy) NSString * callForAuthorizeId;
@property (nonatomic) Card * card;
@property (nonatomic, copy) NSString * currencyId;
@property (nonatomic) NSDate * dateApproved;
@property (nonatomic) NSDate * dateCreated;
@property (nonatomic) NSDate * dateLastUpdated;
@property (nonatomic, copy) NSString * _description;
@property (nonatomic, copy) NSString * externalReference;
@property (nonatomic, copy) NSArray * feesDetails;
@property (nonatomic) NSObject * metadata;
@property (nonatomic) NSDate * moneyReleaseDate;
@property (nonatomic, copy) NSString * notificationUrl;
@property (nonatomic) Order * order;
@property (nonatomic, copy) NSString * paymentMethodId;
@property (nonatomic, copy) NSString * paymentTypeId;
@property (nonatomic, copy) NSArray * refunds;
@property (nonatomic, copy) NSString * statementDescriptor;
@property (nonatomic, copy) NSString * status;
@property (nonatomic, copy) NSString * statusDetail;
@property (nonatomic) TransactionDetails * transactionDetails;
@property (nonatomic, copy) NSString * collectorId;
+ (Payment *)fromJSON:(NSDictionary *)json;
+ (NSDate *)getDateFromString:(NSString *)string;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK24PaymentDateTableViewCell")
@interface PaymentDateTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK22PaymentIDTableViewCell")
@interface PaymentIDTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK13PaymentMethod")
@interface PaymentMethod : NSObject
@property (nonatomic, copy) NSString * id;
@property (nonatomic, copy) NSString * name;
@property (nonatomic, copy) NSString * paymentTypeId;
@property (nonatomic, copy) NSArray * settings;
@property (nonatomic, copy) NSArray * additionalInfoNeeded;
- (BOOL)isIssuerRequired;
- (BOOL)isSecurityCodeRequired:(NSString *)bin;
- (BOOL)isAdditionalInfoNeeded:(NSString *)param;
+ (PaymentMethod *)fromJSON:(NSDictionary *)json;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK16PaymentMethodRow")
@interface PaymentMethodRow : NSObject
@property (nonatomic, copy) NSString * label;
@property (nonatomic) Card * card;
@property (nonatomic, copy) NSString * icon;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK26PaymentMethodTableViewCell")
@interface PaymentMethodTableViewCell : UITableViewCell
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setLabel:(NSString *)label;
- (void)setImageWithName:(NSString *)imageName;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK28PaymentMethodsViewController")
@interface PaymentMethodsViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath;
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath;
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14PaymentService")
@interface PaymentService : MercadoPagoService
- (void)getPaymentMethodsWithMethod:(NSString *)method uri:(NSString *)uri public_key:(NSString *)public_key success:(void (^)(id))success failure:(void (^)(NSError *))failure;
- (void)getIssuersWithMethod:(NSString *)method uri:(NSString *)uri public_key:(NSString *)public_key payment_method_id:(NSString *)payment_method_id success:(void (^)(id))success failure:(void (^)(NSError *))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK25PaymentTotalTableViewCell")
@interface PaymentTotalTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Phone")
@interface Phone : NSObject
@property (nonatomic, copy) NSString * areaCode;
@property (nonatomic, copy) NSString * number;
+ (Phone *)fromJSON:(NSDictionary *)json;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK6Refund")
@interface Refund : NSObject
@property (nonatomic) NSDate * dateCreated;
@property (nonatomic) NSObject * metadata;
@property (nonatomic, copy) NSString * source;
@property (nonatomic, copy) NSString * uniqueSequenceNumber;
+ (Refund *)fromJSON:(NSDictionary *)json;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14SavedCardToken")
@interface SavedCardToken : NSObject
@property (nonatomic, copy) NSString * cardId;
@property (nonatomic, copy) NSString * securityCode;
@property (nonatomic) Device * device;
@property (nonatomic) BOOL securityCodeRequired;
- (instancetype)initWithCardId:(NSString *)cardId securityCode:(NSString *)securityCode OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithCardId:(NSString *)cardId securityCode:(NSString *)securityCode securityCodeRequired:(BOOL)securityCodeRequired OBJC_DESIGNATED_INITIALIZER;
- (BOOL)validate;
- (BOOL)validateCardId;
- (BOOL)validateSecurityCode;
- (NSString *)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK12SecurityCode")
@interface SecurityCode : NSObject
@property (nonatomic, copy) NSString * cardLocation;
@property (nonatomic, copy) NSString * mode;
+ (SecurityCode *)fromJSON:(NSDictionary *)json;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK7Setting")
@interface Setting : NSObject
@property (nonatomic) Bin * bin;
@property (nonatomic) CardNumber * cardNumber;
@property (nonatomic) SecurityCode * securityCode;
+ (Setting *)getSettingByBin:(NSArray *)settings bin:(NSString *)bin;
+ (Setting *)fromJSON:(NSDictionary *)json;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Token")
@interface Token : NSObject
@property (nonatomic, copy) NSString * id;
@property (nonatomic, copy) NSString * publicKey;
@property (nonatomic, copy) NSString * cardId;
@property (nonatomic, copy) NSString * luhnValidation;
@property (nonatomic, copy) NSString * status;
@property (nonatomic, copy) NSString * usedDate;
@property (nonatomic) NSDate * creationDate;
@property (nonatomic, copy) NSString * truncCardNumber;
@property (nonatomic) NSDate * lastModifiedDate;
@property (nonatomic) NSDate * dueDate;
+ (Token *)fromJSON:(NSDictionary *)json;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18TransactionDetails")
@interface TransactionDetails : NSObject
@property (nonatomic, copy) NSString * externalResourceUrl;
@property (nonatomic, copy) NSString * financialInstitution;
+ (TransactionDetails *)fromJSON:(NSDictionary *)json;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIColor (SWIFT_EXTENSION(MercadoPagoSDK))
- (UIColor *)UIColorFromRGB:(NSUInteger)rgbValue;
- (UIColor *)errorCellColor;
- (UIColor *)greenOkColor;
- (UIColor *)redFailureColor;
- (UIColor *)errorValidationTextColor;
- (UIColor *)yellowFailureColor;
- (UIColor *)blueMercadoPago;
- (UIColor *)grayBaseText;
- (UIColor *)grayDark;
- (UIColor *)grayLight;
- (UIColor *)grayLines;
- (UIColor *)backgroundColor;
- (UIColor *)white;
- (UIColor *)installments;
@end


@interface UIDevice (SWIFT_EXTENSION(MercadoPagoSDK))
@end

@class NSString;
@class UILabel;
@class UIActivityIndicatorView;

SWIFT_CLASS("_TtC14MercadoPagoSDK13UILoadingView")
@interface UILoadingView : UIView
- (instancetype)initWithFrame:(CGRect)rect text:(NSString *)text OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) UILabel * label;
@property (nonatomic) UIActivityIndicatorView * spinner;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK19VaultViewController")
@interface VaultViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic) UILoadingView * loadingView;
@property (nonatomic) Card * selectedCard;
@property (nonatomic) PayerCost * selectedPayerCost;
@property (nonatomic) CardToken * selectedCardToken;
@property (nonatomic) PaymentMethod * selectedPaymentMethod;
@property (nonatomic) Issuer * selectedIssuer;
@property (nonatomic) BOOL newCard;
@property (nonatomic, copy) NSArray * cards;
@property (nonatomic, copy) NSArray * payerCosts;
@property (nonatomic) BOOL securityCodeRequired;
@property (nonatomic) NSInteger securityCodeLength;
@property (nonatomic, copy) NSString * bin;
@property (nonatomic, copy) NSArray * supportedPaymentTypes;
- (instancetype)initWithCoder:(NSCoder *)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (void)declareAndInitCells;
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath;
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath;
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath;
- (void)loadPayerCosts;
- (void)submitForm;
@end

#pragma clang diagnostic pop
